/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetablesRouteImport } from './routes/timetables'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as ConstraintsRouteImport } from './routes/constraints'
import { Route as IndexRouteImport } from './routes/index'

const TimetablesRoute = TimetablesRouteImport.update({
  id: '/timetables',
  path: '/timetables',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstraintsRoute = ConstraintsRouteImport.update({
  id: '/constraints',
  path: '/constraints',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/constraints': typeof ConstraintsRoute
  '/faculty': typeof FacultyRoute
  '/generate': typeof GenerateRoute
  '/rooms': typeof RoomsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/timetables': typeof TimetablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/constraints': typeof ConstraintsRoute
  '/faculty': typeof FacultyRoute
  '/generate': typeof GenerateRoute
  '/rooms': typeof RoomsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/timetables': typeof TimetablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/constraints': typeof ConstraintsRoute
  '/faculty': typeof FacultyRoute
  '/generate': typeof GenerateRoute
  '/rooms': typeof RoomsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/timetables': typeof TimetablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/constraints'
    | '/faculty'
    | '/generate'
    | '/rooms'
    | '/students'
    | '/subjects'
    | '/timetables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/constraints'
    | '/faculty'
    | '/generate'
    | '/rooms'
    | '/students'
    | '/subjects'
    | '/timetables'
  id:
    | '__root__'
    | '/'
    | '/constraints'
    | '/faculty'
    | '/generate'
    | '/rooms'
    | '/students'
    | '/subjects'
    | '/timetables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConstraintsRoute: typeof ConstraintsRoute
  FacultyRoute: typeof FacultyRoute
  GenerateRoute: typeof GenerateRoute
  RoomsRoute: typeof RoomsRoute
  StudentsRoute: typeof StudentsRoute
  SubjectsRoute: typeof SubjectsRoute
  TimetablesRoute: typeof TimetablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetables': {
      id: '/timetables'
      path: '/timetables'
      fullPath: '/timetables'
      preLoaderRoute: typeof TimetablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constraints': {
      id: '/constraints'
      path: '/constraints'
      fullPath: '/constraints'
      preLoaderRoute: typeof ConstraintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConstraintsRoute: ConstraintsRoute,
  FacultyRoute: FacultyRoute,
  GenerateRoute: GenerateRoute,
  RoomsRoute: RoomsRoute,
  StudentsRoute: StudentsRoute,
  SubjectsRoute: SubjectsRoute,
  TimetablesRoute: TimetablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
